//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiJinendra {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JaiJinendra.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string aarti_shripanchparmeshthi {
            get {
                return ResourceManager.GetString("aarti_shripanchparmeshthi", resourceCulture);
            }
        }
        
        internal static string aarti_mahavir {
            get {
                return ResourceManager.GetString("aarti_mahavir", resourceCulture);
            }
        }
        
        internal static string aarti_parasnath {
            get {
                return ResourceManager.GetString("aarti_parasnath", resourceCulture);
            }
        }
        
        internal static string aarti_vardhman_swami {
            get {
                return ResourceManager.GetString("aarti_vardhman_swami", resourceCulture);
            }
        }
        
        internal static string aarti_vidyasagar_maharaji {
            get {
                return ResourceManager.GetString("aarti_vidyasagar_maharaji", resourceCulture);
            }
        }
        
        internal static string aarti_neminath_bhagwan {
            get {
                return ResourceManager.GetString("aarti_neminath_bhagwan", resourceCulture);
            }
        }
        
        internal static string aarti_munisuvratnath {
            get {
                return ResourceManager.GetString("aarti_munisuvratnath", resourceCulture);
            }
        }
        
        internal static string aarti_chandraprabhu {
            get {
                return ResourceManager.GetString("aarti_chandraprabhu", resourceCulture);
            }
        }
        
        internal static string aarti_jinvanimata {
            get {
                return ResourceManager.GetString("aarti_jinvanimata", resourceCulture);
            }
        }
        
        internal static string aarti_adinathswami {
            get {
                return ResourceManager.GetString("aarti_adinathswami", resourceCulture);
            }
        }
        
        internal static string aarti_trikaalchaubisi {
            get {
                return ResourceManager.GetString("aarti_trikaalchaubisi", resourceCulture);
            }
        }
        
        internal static string aarti_vasupujya {
            get {
                return ResourceManager.GetString("aarti_vasupujya", resourceCulture);
            }
        }
        
        internal static string aarti_dharmanathbhagwan {
            get {
                return ResourceManager.GetString("aarti_dharmanathbhagwan", resourceCulture);
            }
        }
        
        internal static string aarti_sanmati_prabhu {
            get {
                return ResourceManager.GetString("aarti_sanmati_prabhu", resourceCulture);
            }
        }
        
        internal static string aarti_chandraprabhudeva {
            get {
                return ResourceManager.GetString("aarti_chandraprabhudeva", resourceCulture);
            }
        }
        
        internal static string aarti_shantinath_bhagwan {
            get {
                return ResourceManager.GetString("aarti_shantinath_bhagwan", resourceCulture);
            }
        }
        
        internal static string aarti_sheetalnath_bhagwan {
            get {
                return ResourceManager.GetString("aarti_sheetalnath_bhagwan", resourceCulture);
            }
        }
        
        internal static string stotrahindi_bhaktamar {
            get {
                return ResourceManager.GetString("stotrahindi_bhaktamar", resourceCulture);
            }
        }
        
        internal static string stotrahindi_merebhawna {
            get {
                return ResourceManager.GetString("stotrahindi_merebhawna", resourceCulture);
            }
        }
        
        internal static string stotrahindi_barahbhavna {
            get {
                return ResourceManager.GetString("stotrahindi_barahbhavna", resourceCulture);
            }
        }
        
        internal static string stotrahindi_vairagyaBhavna {
            get {
                return ResourceManager.GetString("stotrahindi_vairagyaBhavna", resourceCulture);
            }
        }
        
        internal static string stotrahindi_AlochanaPath {
            get {
                return ResourceManager.GetString("stotrahindi_AlochanaPath", resourceCulture);
            }
        }
        
        internal static string stotrahindi_dukhharanvinti {
            get {
                return ResourceManager.GetString("stotrahindi_dukhharanvinti", resourceCulture);
            }
        }
        
        internal static string stotrahindi_SamayikPath {
            get {
                return ResourceManager.GetString("stotrahindi_SamayikPath", resourceCulture);
            }
        }
        
        internal static string stotra_bhaktamar {
            get {
                return ResourceManager.GetString("stotra_bhaktamar", resourceCulture);
            }
        }
        
        internal static string stotra_parasnath {
            get {
                return ResourceManager.GetString("stotra_parasnath", resourceCulture);
            }
        }
        
        internal static string stotra_mahavirastak {
            get {
                return ResourceManager.GetString("stotra_mahavirastak", resourceCulture);
            }
        }
        
        internal static string stotra_kalyan_mandir {
            get {
                return ResourceManager.GetString("stotra_kalyan_mandir", resourceCulture);
            }
        }
        
        internal static string stotra_ekibhav {
            get {
                return ResourceManager.GetString("stotra_ekibhav", resourceCulture);
            }
        }
        
        internal static string stotra_darshan_path {
            get {
                return ResourceManager.GetString("stotra_darshan_path", resourceCulture);
            }
        }
        
        internal static string bhakti_acharyabhakti {
            get {
                return ResourceManager.GetString("bhakti_acharyabhakti", resourceCulture);
            }
        }
        
        internal static string bhakti_acharyavandana {
            get {
                return ResourceManager.GetString("bhakti_acharyavandana", resourceCulture);
            }
        }
        
        internal static string bhakti_acharyabhaktisanskrit {
            get {
                return ResourceManager.GetString("bhakti_acharyabhaktisanskrit", resourceCulture);
            }
        }
        
        internal static string bhakti_bhawnaDwatrishantika {
            get {
                return ResourceManager.GetString("bhakti_bhawnaDwatrishantika", resourceCulture);
            }
        }
        
        internal static string stuti_aradhanapath {
            get {
                return ResourceManager.GetString("stuti_aradhanapath", resourceCulture);
            }
        }
        
        internal static string stuti_atamkirtan_ {
            get {
                return ResourceManager.GetString("stuti_atamkirtan ", resourceCulture);
            }
        }
        
        internal static string stuti_alochanapath {
            get {
                return ResourceManager.GetString("stuti_alochanapath", resourceCulture);
            }
        }
        
        internal static string stuti_amulyatatvavichar {
            get {
                return ResourceManager.GetString("stuti_amulyatatvavichar", resourceCulture);
            }
        }
        
        internal static string stuti_bhaubalistuti {
            get {
                return ResourceManager.GetString("stuti_bhaubalistuti", resourceCulture);
            }
        }
        
        internal static string stuti_bhaktamarmahima {
            get {
                return ResourceManager.GetString("stuti_bhaktamarmahima", resourceCulture);
            }
        }
        
        internal static string stuti_chubisiteerthankarvandana {
            get {
                return ResourceManager.GetString("stuti_chubisiteerthankarvandana", resourceCulture);
            }
        }
        
        internal static string stuti_darshanpath {
            get {
                return ResourceManager.GetString("stuti_darshanpath", resourceCulture);
            }
        }
        
        internal static string stuti_darshanstuti {
            get {
                return ResourceManager.GetString("stuti_darshanstuti", resourceCulture);
            }
        }
        
        internal static string stuti_prabhupatitpavan {
            get {
                return ResourceManager.GetString("stuti_prabhupatitpavan", resourceCulture);
            }
        }
        
        internal static string stuti_samadhibhwana {
            get {
                return ResourceManager.GetString("stuti_samadhibhwana", resourceCulture);
            }
        }
        
        internal static string stuti_samadhipath {
            get {
                return ResourceManager.GetString("stuti_samadhipath", resourceCulture);
            }
        }
        
        internal static string stuti_shrishiddhchakra {
            get {
                return ResourceManager.GetString("stuti_shrishiddhchakra", resourceCulture);
            }
        }
        
        internal static string stuti_tumselagilagan {
            get {
                return ResourceManager.GetString("stuti_tumselagilagan", resourceCulture);
            }
        }
        
        internal static string arghavali_devshastraguru {
            get {
                return ResourceManager.GetString("arghavali_devshastraguru", resourceCulture);
            }
        }
        
        internal static string arghavali_vidyamanabeesteethankar {
            get {
                return ResourceManager.GetString("arghavali_vidyamanabeesteethankar", resourceCulture);
            }
        }
        
        internal static string arghavali_kritrimaakritima {
            get {
                return ResourceManager.GetString("arghavali_kritrimaakritima", resourceCulture);
            }
        }
        
        internal static string arghavali_siddhparmaesti {
            get {
                return ResourceManager.GetString("arghavali_siddhparmaesti", resourceCulture);
            }
        }
        
        internal static string arghavali_teeschaubisi {
            get {
                return ResourceManager.GetString("arghavali_teeschaubisi", resourceCulture);
            }
        }
        
        internal static string arghavali_shriaadinathji {
            get {
                return ResourceManager.GetString("arghavali_shriaadinathji", resourceCulture);
            }
        }
        
        internal static string arghavali_sriajitanathjinendra {
            get {
                return ResourceManager.GetString("arghavali_sriajitanathjinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srisambhavanathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srisambhavanathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_sriabhinandananatha {
            get {
                return ResourceManager.GetString("arghavali_sriabhinandananatha", resourceCulture);
            }
        }
        
        internal static string arghavali_srisumatinatha {
            get {
                return ResourceManager.GetString("arghavali_srisumatinatha", resourceCulture);
            }
        }
        
        internal static string arghavali_sripadmaprabhajinendra {
            get {
                return ResourceManager.GetString("arghavali_sripadmaprabhajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srisuparshvanatha {
            get {
                return ResourceManager.GetString("arghavali_srisuparshvanatha", resourceCulture);
            }
        }
        
        internal static string arghavali_srichandraprahajinendra {
            get {
                return ResourceManager.GetString("arghavali_srichandraprahajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_sripuspadantajnendra {
            get {
                return ResourceManager.GetString("arghavali_sripuspadantajnendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srisheetalnathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srisheetalnathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srisreyansanatha {
            get {
                return ResourceManager.GetString("arghavali_srisreyansanatha", resourceCulture);
            }
        }
        
        internal static string arghavali_srivasupujyajinendra {
            get {
                return ResourceManager.GetString("arghavali_srivasupujyajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srivimalanatha {
            get {
                return ResourceManager.GetString("arghavali_srivimalanatha", resourceCulture);
            }
        }
        
        internal static string arghavali_srinantanatha {
            get {
                return ResourceManager.GetString("arghavali_srinantanatha", resourceCulture);
            }
        }
        
        internal static string arghavali_sridharmanathajinendra {
            get {
                return ResourceManager.GetString("arghavali_sridharmanathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srishantinathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srishantinathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srikunthunathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srikunthunathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_sriarahnathajinendra {
            get {
                return ResourceManager.GetString("arghavali_sriarahnathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srimallinathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srimallinathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srimunisuvratajinendra {
            get {
                return ResourceManager.GetString("arghavali_srimunisuvratajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srinaminathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srinaminathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_srineminathajinendra {
            get {
                return ResourceManager.GetString("arghavali_srineminathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_sriparavanathajinendra {
            get {
                return ResourceManager.GetString("arghavali_sriparavanathajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_shimahavirajinendra {
            get {
                return ResourceManager.GetString("arghavali_shimahavirajinendra", resourceCulture);
            }
        }
        
        internal static string arghavali_bhaubaliswami {
            get {
                return ResourceManager.GetString("arghavali_bhaubaliswami", resourceCulture);
            }
        }
        
        internal static string arghavali_panchbalayati {
            get {
                return ResourceManager.GetString("arghavali_panchbalayati", resourceCulture);
            }
        }
        
        internal static string arghavali_solahakaranabhavana {
            get {
                return ResourceManager.GetString("arghavali_solahakaranabhavana", resourceCulture);
            }
        }
        
        internal static string arghavali_panchamerujinalayon {
            get {
                return ResourceManager.GetString("arghavali_panchamerujinalayon", resourceCulture);
            }
        }
        
        internal static string arghavali_nandisvaradvipajinalayon {
            get {
                return ResourceManager.GetString("arghavali_nandisvaradvipajinalayon", resourceCulture);
            }
        }
        
        internal static string arghavali_dasalaksanadharma {
            get {
                return ResourceManager.GetString("arghavali_dasalaksanadharma", resourceCulture);
            }
        }
        
        internal static string arghavali_srisamyakratntraya {
            get {
                return ResourceManager.GetString("arghavali_srisamyakratntraya", resourceCulture);
            }
        }
        
        internal static string arghavali_saptarishi {
            get {
                return ResourceManager.GetString("arghavali_saptarishi", resourceCulture);
            }
        }
        
        internal static string arghavali_srichaubisatirthankaranirvanaksetra {
            get {
                return ResourceManager.GetString("arghavali_srichaubisatirthankaranirvanaksetra", resourceCulture);
            }
        }
        
        internal static string arghavali_samedhshikarji {
            get {
                return ResourceManager.GetString("arghavali_samedhshikarji", resourceCulture);
            }
        }
        
        internal static string arghavali_sarasvatimata {
            get {
                return ResourceManager.GetString("arghavali_sarasvatimata", resourceCulture);
            }
        }
        
        internal static string arghavali_srimandala {
            get {
                return ResourceManager.GetString("arghavali_srimandala", resourceCulture);
            }
        }
        
        internal static string arghavali_bharteshwarswami {
            get {
                return ResourceManager.GetString("arghavali_bharteshwarswami", resourceCulture);
            }
        }
        
        internal static string arghavali_gautamswamiji {
            get {
                return ResourceManager.GetString("arghavali_gautamswamiji", resourceCulture);
            }
        }
        
        internal static string arghavali_jambuswamiji {
            get {
                return ResourceManager.GetString("arghavali_jambuswamiji", resourceCulture);
            }
        }
        
        internal static string arghavali_aantaranashai {
            get {
                return ResourceManager.GetString("arghavali_aantaranashai", resourceCulture);
            }
        }
        
        internal static string arghavali_maansthimbhji {
            get {
                return ResourceManager.GetString("arghavali_maansthimbhji", resourceCulture);
            }
        }
    }
}
