//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiJinendra.StringResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChalisaResources_hi {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChalisaResources_hi() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JaiJinendra.StringResources.ChalisaResources.hi", typeof(ChalisaResources_hi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AdinathChalisa {
            get {
                return ResourceManager.GetString("AdinathChalisa", resourceCulture);
            }
        }
        
        internal static string AjitnathChalisa {
            get {
                return ResourceManager.GetString("AjitnathChalisa", resourceCulture);
            }
        }
        
        internal static string SambhavnathChalisa {
            get {
                return ResourceManager.GetString("SambhavnathChalisa", resourceCulture);
            }
        }
        
        internal static string AbhinandannathChalisa {
            get {
                return ResourceManager.GetString("AbhinandannathChalisa", resourceCulture);
            }
        }
        
        internal static string SumatinathChalisa {
            get {
                return ResourceManager.GetString("SumatinathChalisa", resourceCulture);
            }
        }
        
        internal static string Padamprabhuji {
            get {
                return ResourceManager.GetString("Padamprabhuji", resourceCulture);
            }
        }
        
        internal static string SuparasnathChalisa {
            get {
                return ResourceManager.GetString("SuparasnathChalisa", resourceCulture);
            }
        }
        
        internal static string ChandaprabhuChalisa {
            get {
                return ResourceManager.GetString("ChandaprabhuChalisa", resourceCulture);
            }
        }
        
        internal static string PushpdantChalisa {
            get {
                return ResourceManager.GetString("PushpdantChalisa", resourceCulture);
            }
        }
        
        internal static string ShantinathChalisa {
            get {
                return ResourceManager.GetString("ShantinathChalisa", resourceCulture);
            }
        }
    }
}
